# Generated by Django 2.0.5 on 2018-05-25 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
